---
- name: Configure Windows 2019 Server as Domain Controller
  hosts: domain_controller
  gather_facts: yes
  tasks:
    - name: Install Active Directory and DNS Server Role
      win_feature:
        name:
          - AD-Domain-Services
          - DNS
        include_management_tools: yes
        include_sub_features: yes
        state: present
      register: result

    - name: Change Administrator password
      ansible.windows.win_user:
        name: Administrator
        password: "{{ da_password }}"

    - name: Create traininglab.local domain
      win_domain:
        dns_domain_name: traininglab.local
        domain_netbios_name: TRAINING
        safe_mode_password: "{{ safe_mode_pass }}"
      register: ad

    - name: Reboot Domain Controller to apply changes
      ansible.windows.win_reboot:
      when: ad.reboot_required

    - name: Set internal DNS server 
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
        - '127.0.0.1'

    - name: Configure DNS forwarders
      ansible.windows.win_powershell:
        script: |
          Set-DNSServerForwarder -IPAddress 1.1.1.1