---
- name: Install Wazuh everywhere
  hosts: domain_controller, workstations, fileserver
  tasks:
    - name: Install 
      args:
        chdir: C:\Users\{{ ansible_user }}\Downloads
      ansible.windows.win_powershell: 
        script: |
          Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.5.1-1.msi -OutFile ${env:tmp}\wazuh-agent.msi; msiexec.exe /i ${env:tmp}\wazuh-agent.msi /q WAZUH_MANAGER='<monitoring_server>' WAZUH_REGISTRATION_SERVER='<monitoring_server>' WAZUH_AGENT_GROUP='default'

    - name: Start Wazuh
      ansible.windows.win_service:
        name: WazuhSvc
        start_mode: auto
        state: started