# just a workaround :)
---
- name: Doing some magic to prepare windows hosts
  hosts: domain_controller, workstations, fileserver
  gather_facts: yes
  tasks:
  - name: Disable Hibernation using win_regedit
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Power
      name: HibernateFileSizePercent
      data: 0
      datatype: dword
      state: present
    register: deactive
      
  - name: Disable Hibernation using win_regedit
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Power
      name: HibernateEnabled
      data: 0
      datatype: dword
      state: present

  - name: Reboot before domain creation
    ansible.windows.win_reboot:
    when: deactive.changed
