# just a workaround :)
---
- name: Doing some magic to prepare windows hosts
  hosts: domain_controller, workstations, fileserver
  gather_facts: yes
  tasks:
  - name: Disable Hibernation using win_regedit
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Power
      name: HibernateFileSizePercent
      data: 0
      datatype: dword
      state: present
    register: deactive
      
  - name: Disable Hibernation using win_regedit
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Power
      name: HibernateEnabled
      data: 0
      datatype: dword
      state: present

  - name: Disable windows defender sending sample
    ansible.windows.win_powershell: 
      script: |
        Set-MpPreference -MAPSReporting 0; Set-MpPreference -SubmitSamplesConsent 2; Set-MpPreference -DisableRealtimeMonitoring $true; Set-MpPreference -DisableScanningMappedNetworkDrivesForFullScan $true

  - name: Allow Remote Desktop Users to use RDP
    ansible.windows.win_user_right:
      name: SeRemoteInteractiveLogonRight
      users:
      - Administrators
      - Remote Desktop Users

  - name: Allow RDP Connections
    ansible.windows.win_regedit:
      path: HKLM:\System\CurrentControlSet\Control\Terminal Server
      name: fDenyTSConnections
      data: 0
      datatype: dword
      state: present

  - name: Firewall rule to allow RDP on TCP port 3389
    community.windows.win_firewall_rule:
      name: Remote Desktop
      localport: 3389
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes

  - name: Reboot before domain creation
    ansible.windows.win_reboot:
    when: deactive.changed
